// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64(),
  playerId: __t.u64(),
  isWinner: __t.bool(),
  isLoser: __t.bool(),
  isHost: __t.bool(),
  isCurrentTurn: __t.bool(),
  wrongGuessCount: __t.u32(),
  score: __t.i32(),
  joinedAt: __t.timestamp(),
});
